const copy={tr:{subtitle:"Canlı ölçüm",language:"Dil",profile:"Dedektör profili",device:"Giriş aygıtı",threshold:"Tetikleme eşiği",start:"Kaydı başlat",stop:"Durdur ve dışa aktar",rate:"Sayım hızı",amplitude:"Darbe genliği",total:"Toplam",idle:"Mikrofonu bağlayıp kaydı başlatın.",running:"Kayıt sürüyor.",permission:"Mikrofon erişimi reddedildi. Tarayıcı ayarlarından izin verin.",deviceError:"Ses girişi kullanılamıyor. Başka bir aygıt seçin.",axis:"Genlik ekseni. keV/MeV için iki kullanıcı referans noktasıyla kalibrasyon gerekir.",electron:"Elektron / beta dedektörü",alpha:"Alfa spektrometresi",default:"Varsayılan"},en:{subtitle:"Live measurement",language:"Language",profile:"Detector profile",device:"Input device",threshold:"Trigger threshold",start:"Start recording",stop:"Stop and export",rate:"Count rate",amplitude:"Pulse amplitude",total:"Total",idle:"Connect the microphone, then start recording.",running:"Recording in progress.",permission:"Microphone access was denied. Allow it in browser settings.",deviceError:"The audio input is unavailable. Choose another device.",axis:"Amplitude axis. Add two user reference points before enabling keV/MeV.",electron:"Electron / beta detector",alpha:"Alpha spectrometer",default:"Default"}};
let lang=navigator.language.startsWith("tr")?"tr":"en",stream,context,analyser,raf,started,pulses=[],latest=[];const $=id=>document.getElementById(id),text=(id,key)=>$(id).textContent=copy[lang][key];
function translate(){document.documentElement.lang=lang;[["subtitle","subtitle"],["language-label","language"],["profile-label","profile"],["device-label","device"],["threshold-label","threshold"],["start","start"],["stop","stop"],["rate-label","rate"],["amplitude-label","amplitude"],["total-label","total"],["axis","axis"]].forEach(([a,b])=>text(a,b));$("profile").options[0].text=copy[lang].electron;$("profile").options[1].text=copy[lang].alpha;$("device").options[0].text=copy[lang].default;if(!stream)$("message").textContent=copy[lang].idle;}
async function devices(){try{const all=await navigator.mediaDevices.enumerateDevices(),select=$("device");select.length=1;all.filter(d=>d.kind==="audioinput").forEach(d=>select.add(new Option(d.label||"Audio input",d.deviceId)));}catch(_){}}
function draw(){const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);const c=$("scope"),ctx=c.getContext("2d"),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.clearRect(0,0,w,h);ctx.strokeStyle="#35d0ba";ctx.beginPath();data.forEach((v,i)=>{let x=i*w/(data.length-1),y=h/2-v*h*.45;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();const minimum=Math.min(...data)*32768,threshold=Number($("threshold").value);if(minimum<threshold){const waveform=Array.from(data,x=>Math.round(x*32768)),now=Date.now();if(!pulses.length||now-pulses[pulses.length-1].timestamp_us/1000>2){pulses.push({timestamp_us:now*1000,peak:minimum,waveform});latest.push(now);$("amplitude").textContent=Math.round(minimum);$("total").textContent=pulses.length;}}latest=latest.filter(t=>Date.now()-t<10000);$("rate").textContent=(latest.length/10).toFixed(2)+" CPS";raf=requestAnimationFrame(draw);}
async function start(){try{const selected=$("device").value;stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:selected?{exact:selected}:undefined},video:false});context=new AudioContext({sampleRate:48000});analyser=context.createAnalyser();analyser.fftSize=$("profile").value==="alpha"?2048:256;context.createMediaStreamSource(stream).connect(analyser);started=new Date().toISOString();pulses=[];latest=[];$("start").disabled=true;$("stop").disabled=false;$("message").textContent=copy[lang].running;await devices();draw();}catch(error){$("message").textContent=error.name==="NotAllowedError"?copy[lang].permission:copy[lang].deviceError;}}
function calibration(){const values=[["reference-a","energy-a"],["reference-b","energy-b"]].map(([a,e])=>[Number($(a).value),Number($(e).value)]);if(values.every(([a,e])=>a>0&&e>0)&&values[0][0]!==values[1][0]&&((values[1][1]-values[0][1])/(values[1][0]-values[0][0])>0)){return values;}return null;}
function stop(){cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());const rate=context?.sampleRate||48000;context?.close();stream=null;$("start").disabled=false;$("stop").disabled=true;if(pulses.length){const data={format:"pdet",version:1,session:{started_at:started,sample_rate:rate,profile:$("profile").value,lost_samples:0,calibration:calibration()},pulses};saveAs(new Blob([msgpack.serialize(data)],{type:"application/octet-stream"}),"particle-detector.pdet");}$("message").textContent=copy[lang].idle;}
$("language").value=lang;$("language").onchange=e=>{lang=e.target.value;translate()};$("start").onclick=start;$("stop").onclick=stop;$("profile").onchange=e=>$("threshold").value=e.target.value==="alpha"?-300:-800;navigator.mediaDevices.addEventListener("devicechange",devices);translate();devices();
